### ISSUE TITLE
WalletSecret::generate_sender_randomness() is not unique per output or even per Tx.

### ISSUE THREAD

**Issue by dan-da** [Neptune-Crypto/neptune-core#181] opened 2024-09-01 00:33 UTC
Here is the method signature:

```
    /// Return the secret key that is used to deterministically generate commitment pseudo-randomness
    /// for the mutator set.
    pub fn generate_sender_randomness(
        &self,
        block_height: BlockHeight,
        receiver_digest: Digest,
    ) -> Digest {
```

This means that `sender_randomness` will be the same for every output of every tx for a given block that is destined for the same receiver.

My expectation until now has been that `sender_randomness` would be different for every output, period.  That could be achieved deterministically with some type of counter or non-deterministically.

It is not clear to me why it should be deterministic.  maybe there is a good reason?

### how I found it

I've been testing the claim_utxo() RPC for offchain-serialization feature I am presently working on.  claim_utxo() accepts a utxo and sender_randomness and searches existing ExpectedUtxo to see if one already exists or a new one should be added.

I was surprised to find that when I sent funds to myself in tx A and again in tx B that the claim for tx B would fail with an error message that the claim had already been performed.

Investigating the cause I found this issue with `generate_sender_randomness()`.

My intuition is to fix it by making `sender_randomness` truly random.   I don't see that it even needs to care about the `block_height` or `receiver_digest`.   However, it was written that way for a reason so thus I am creating this issue for discussion rather than just making such a change blindly.

**Comment by dan-da** [comment] 2024-09-01 01:49
I made a quick test where I modified generate_sender_randomness() to simply return rand::random().

```
    pub fn generate_sender_randomness(&self, _bh: BlockHeight, _rd: Digest) -> Digest {
        rand::random()
    }
```

I then ran all unit tests with `cargo test` and everything passes. 

Then I performed my claim_utxo procedure twice with outputs from two separate TX exactly as before and now the second one is claimed correctly.

In other words, it seems to be fine and fixes the issue.

But maybe there is some problem with using a random digest that I'm not seeing and tests aren't picking up?

**Comment by aszepieniec** [comment] 2024-09-10 15:18
> It is not clear to me why it should be deterministic. maybe there is a good reason?

If I wrote it, it was a long time ago. Either way, I can only guess at the reason -- any my guess is that we want to avoid situations where UTXOs are unspendable because the sender randomness was lost. Making the sender randomness deterministic can achieve this, because if you lose it you just ask the sender to re-send the randomness.

The purpose of the sender randomness is to randomize the appearance of the removal record, together with the receiver preimage, the UTXO, and the index of the UTXO's insertion into the AOCL. Two removal records for different UTXOs can never look alike because the index of insertion into the AOCL is necessarily different. (And under normal circumstances all four fields are different.) So there is no risk of undermining unlinkability between removal records, even if two removal records spend identical UTXOs and were transmitted with identical sender randomness and identical receiver digests.

One feature that is achieved by including sender randomness is post-compromise plausible deniability. Suppose there is a mafia writ-large mandating unhosted wallet operators to relay their receiver preimages to some mafia-designated authority for monitoring purposes. This authority won't be able to spend its victims' funds because it doesn't entail transmitting the unlock keys, and so since this edict is not outrageous enough most people simply comply with the edict.  As long as that authority doesn't know the sender randomness, they still won't know that their victims received anything. And nor can the victim be required to make all transfers headed to them display a subliminal flag because the receiver is *not* in control of what the removal record looks like.

I'm sure there are other features achieved by sender randomness, but they will all be roughly as niche as the one described above. The point of the long story is that it's not a big problem if sender randomnesses are sometimes repeated.

**Comment by dan-da** [comment] 2024-09-10 16:48
ok, thx for adding this context.

> The point of the long story is that it's not a big problem if sender randomnesses are sometimes repeated.

cool, not a problem for consensus/correctness.

But I am still left with a decision how to handle the issue for claiming.

I stated above:

> I've been testing the claim_utxo() RPC for offchain-serialization feature I am presently working on. claim_utxo() accepts a utxo and sender_randomness and searches existing ExpectedUtxo to see if one already exists or a new one should be added.
>
> I was surprised to find that when I sent funds to myself in tx A and again in tx B that the claim for tx B would fail with an error message that the claim had already been performed.

So I need  a way to make the (utxo, sender_randomness) pair unique.  Since utxo has nothing unique/random about it, that means that sender_randomness must be unique.  And indeed its very name indicates it is supposed to be random.

So I think I will make it random for this PR.   If there is further discussion/objection (here or in the PR) then the alternative would be to try and find a way to make it deterministically unique using some kind of known value, though I don't immediately see what it would be.

**Comment by dan-da** [comment] 2024-09-11 02:31
hmm... I'm re-thinking this a bit.

I'm trying to think of use-cases where the recipient could somehow lose the sender_randomness and need the sender to send it again.

of course even with a purely random value, the sender could resend it provided s/he stores it somewhere.   So keeping a sender_randomness store is another possibility, albeit grosser than if sender can just regenerate it from other known data.

One area where it can be required is with offchain utxo-transfers.  In this case, the recipient may lose (or never receive) the entire notification (which includes sender_randomness).  So they need sender to provide the notification again.   For this reason neptune-cli is automatically storing the transfer files.

Unfortunately I do not presently have a way for the sender to regenerate the utxo-notification if s/he loses the transfer file.   Simply creating a new transaction with the same nominal outputs is insufficient as it would use different (unspent) inputs and create new output utxos.

So this use-case is related, but larger than just sender_randomness.

Anyway, if we want sender_randomness to be deterministic then I think it should probably also include the tx timestamp and the output index.   That makes it harder to create a dup... one has to intentionally do it, eg by creating two tx with the same timestamp.

This would requiring passing around tx timestamp in some methods that currenctly do not require it, but may be worth it.

still thinking about it.

It would help to have a clear scenario of how recipient could lose sender_randomness.  For onchain transfers, it doesn't seem possible.   So I guess this is more of an offchain/L2 type of consideration....

**Comment by aszepieniec** [comment] 2024-09-11 12:27
> I was surprised to find that when I sent funds to myself in tx A and again in tx B that the claim for tx B would fail with an error message that the claim had already been performed.

This failure needs to be fixed on the side of the receiver, not on the side of sender. Third parties are allowed to write their own implementations of Neptune wallets and some of those third parties will generate sender randomnesses deterministically (and perhaps even in a less secure way than the present code). The receiver's wallet should be capable of claiming identical but independently confirmed UTXOs, no matter how the sender randomness is set.

Requiring the sender randomness to be random, or even just unique, on the sender side, in order to solve a difficulty encountered on the receiver side, is a bad design.

**Comment by dan-da** [comment] 2024-09-12 02:02
thx for pointing this out.  I was able to modify the receiving code to not rely on the sender_randomness being unique.

Back to the original question of deterministic vs non-deterministic sender_randomness:

I discovered that the receiver_digest param is only really used as intended when the utxo recipient is a ReceivingAddress.   In other cases such as LockScript::anyone_can_spend(), the unit-test code is always passing random() for the receiver_digest field which makes the sender_randomness non-deterministic anyway.   This asymmetry bothers me a little, but does not appear to be an actual problem, per above statements.

Also, I experimented with adding params: tx_timestamp and output_index to reduce the chance of dups.   While this works, afaict it also defeats the stated goal that the sender could re-create the sender randomness later.   This is because after the user-tx is confirmed in a block it becomes merged into a block-tx.   The timestamp is lost and the output index changes.

So I begin to see why the parameters are just `block_height` and `receiver_digest`.

This issue may be worth revisiting later.  But for now I have just documented the above for sender_randomness, and added a link to this issue, so it's clearer for the next person looking at it.

**Closed** 2024-09-15 01:12 UTC
