### ISSUE TITLE
Pause Mining while Initiating Transaction

### ISSUE THREAD

**Issue by aszepieniec** [Neptune-Crypto/neptune-core#20] opened 2023-07-18 19:46 UTC
When mining (without throttling), one CPU is used at full capacity. When initiating a transaction, a proof is generated and *all* CPUs are needed. So it may cause scheduling conflicts when we are mining (without throttling) and initiating a transaction. I have seen a node crash when attempting to do this and I suspect scheduling conflicts is the problem.
 - [ ] pause mining while initiating a transaction

**Comment by dan-da** [comment] 2024-02-18 00:45
I think that pausing mining would be a band-aid for the real problem, whatever it is, which should be fixed.

It is possible that the problem is already fixed in more recent code.  In particular, the locking has been re-worked and is much simpler now.

Leaving open for now.   Will attempt to reproduce another time.

**Comment by Sword-Smith** [comment] 2024-12-18 10:18
Closed by adding the `no_transaction_initiation` flag to the CLI options in `93f145bea2173c8562061d014468cc5323e0ff79`. This is now the user's responsibility to handle. Also: All proving is guaranteed to run serially, i.e. one proof at a time, such that the client does not attempt to produce two STARK proofs simultaneously. This guarantee is given by the `job_queue` functionality.

**Closed by Sword-Smith** 2024-12-18 10:18 UTC
